exports.TAG = 'MechaRichy';
exports.JDB_NAME = 'mecha-richy-data';
exports.JDB_TX_STORE = 'Transaction';
exports.JDB_BLOCK_STORE = 'Block';
exports.BLOCKS_CACHING_ENABLED = true;
exports.BLOCKS_CACHE_SIZE = 0;
exports.BLOCKS_RAW_CACHE_SIZE = 500;
exports.DB_VERSION = 8;
exports.INITIAL_DB_SIZE = 1024*1024*500; // 500 MB initially
exports.MIN_RESIZE = 1 << 30; // 1 GB
exports.STATE_ENGINE_INITIALIZED = 'initialized';
exports.STATE_ENGINE_READY = 'ready';